version: "3"

services:
    haproxy:
        image: dockercloud/haproxy
        links:
            - es1
            - es2
            - es3
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9200:80"
            - "9300:9300"
        environment:
            - TCP_PORTS="9300"
        restart: unless-stopped
        network_mode: bridge
    es3:
        image: jplu/elasticsearch
        volumes:
            - $HOME/elasticsearch/data/es3:/elasticsearch/data
        privileged: true
        environment:
            - NODE_MASTER=false
            - CLUSTER_NAME=elasticsearch
            - ES_JAVA_OPTS=-Xmx31767m -Xms31767m
            - USER=semantic
            - ID=1000
            - UNICAST_HOSTS=es1,es2
            - TCP_PORTS=9300
        links:
            - es1
            - es2
        hostname: es3
        restart: unless-stopped
        expose:
            - "9200"
            - "9300"
        network_mode: bridge
    es2:
        image: jplu/elasticsearch
        volumes:
            - $HOME/elasticsearch/data/es2:/elasticsearch/data
        privileged: true
        environment:
            - NODE_MASTER=false
            - CLUSTER_NAME=elasticsearch
            - ES_JAVA_OPTS=-Xmx31767m -Xms31767m
            - USER=semantic
            - ID=1000
            - UNICAST_HOSTS=es1
            - TCP_PORTS=9300
        links:
            - es1
        hostname: es2
        restart: unless-stopped
        expose:
            - "9200"
            - "9300"
        network_mode: bridge
    es1:
        image: jplu/elasticsearch
        volumes:
           - $HOME/elasticsearch/data/es1:/elasticsearch/data
        privileged: true
        environment:
            - CLUSTER_NAME=elasticsearch
            - ES_JAVA_OPTS=-Xmx31767m -Xms31767m
            - USER=semantic
            - ID=1000
            - TCP_PORTS=9300
        expose:
            - "9300"
            - "9200"
        hostname: es1
        restart: unless-stopped
        network_mode: bridge